-- lessons.lua — all tutor content

return {
  {
    name = 'First Steps',
    icon = '🚀',
    desc = 'Launch your first Telescope pickers',
    challenges = {
      {
        id = 'sf', title = 'File Finder', mission = 'Open the file finder',
        body = {
          'Search all files in your project by name.',
          'Start typing to fuzzy-filter results instantly.',
          '',
          '  Keymap:  <leader>sf',
          '  Hint:    Space → s → f',
        },
        type = 'keymap', key = '<leader>sf',
        tip = '  <leader>sf is your most-used picker. Fuzzy matching\n  means typos are fine — "inlua" finds "init.lua".',
        xp = 100, time_stars = { 5, 15, 45 },
      },
      {
        id = 'sg', title = 'Live Grep', mission = 'Search text across all files',
        body = {
          'Grep through your entire project in real-time.',
          'Useful for finding where a function is called.',
          '',
          '  Keymap:  <leader>sg',
          '  Hint:    Space → s → g',
        },
        type = 'keymap', key = '<leader>sg',
        tip = '  Inside live_grep, use <C-f> to switch to file-path\n  filtering mode (filter by filename instead of content).',
        xp = 100, time_stars = { 5, 15, 45 },
      },
      {
        id = 'buffers', title = 'Buffer Switcher', mission = 'Open the buffer list',
        body = {
          'Quickly switch between files you already have open.',
          '',
          '  Keymap:  <leader><leader>   (Space twice)',
        },
        type = 'keymap', key = '<leader><leader>',
        tip = '  In the buffer picker, press <C-d> to delete a buffer\n  without leaving Telescope.',
        xp = 100, time_stars = { 5, 15, 45 },
      },
      {
        id = 'nav_quiz', title = 'Navigator', mission = 'How do you move DOWN in a picker?',
        body = {
          'You\'re in a Telescope picker in insert mode.',
          'How do you move DOWN the results list without',
          'reaching for the arrow keys?',
          '',
          '  [1]  Ctrl+j  or  Ctrl+n',
          '  [2]  Ctrl+d',
          '  [3]  Tab',
          '  [4]  Alt+Down',
        },
        type = 'quiz', answer = '1',
        explanation = '  <C-n> / <C-j>  move down\n  <C-p> / <C-k>  move up\n  In normal mode (press Esc first), j/k also work.',
        xp = 75,
      },
      {
        id = 'split_quiz', title = 'Split Master', mission = 'Open selection in a vertical split?',
        body = {
          'You\'re in a Telescope picker and want to open',
          'the selected file in a vertical split.',
          '',
          '  [1]  Ctrl+s',
          '  [2]  Ctrl+v',
          '  [3]  Alt+v',
          '  [4]  v  (in normal mode)',
        },
        type = 'quiz', answer = '2',
        explanation = '  <C-v>  open in vertical split\n  <C-x>  open in horizontal split\n  <C-t>  open in new tab\n  <CR>   open in current window',
        xp = 75,
      },
    },
  },
  {
    name = 'Getting Fluent',
    icon = '⚡',
    desc = 'Master pickers you\'ll use every day',
    challenges = {
      {
        id = 'sh', title = 'Help Search', mission = 'Search all Neovim help',
        body = {
          'Fuzzy-search all :help tags instantly.',
          'Much faster than :help <Tab> completion.',
          '',
          '  Keymap:  <leader>sh',
          '  Hint:    Space → s → h',
        },
        type = 'keymap', key = '<leader>sh',
        tip = '  <leader>sh searches help tags. Once open, press\n  <CR> to jump directly to the help page.',
        xp = 100, time_stars = { 5, 15, 45 },
      },
      {
        id = 'sr', title = 'Resume', mission = 'Resume your last Telescope search',
        body = {
          'Return to the last picker — same query, same',
          'position. Useful when you close by accident.',
          '',
          '  Keymap:  <leader>sr',
          '  Hint:    Space → s → r',
        },
        type = 'keymap', key = '<leader>sr',
        tip = '  <leader>sr resumes the last picker session.\n  Works across picker types (grep, files, etc.).',
        xp = 100, time_stars = { 5, 15, 45 },
      },
      {
        id = 'ss', title = 'Meta Picker', mission = 'Open the picker-of-all-pickers',
        body = {
          'Browse and launch any Telescope built-in picker.',
          'Great for discovering ones you\'ve never used.',
          '',
          '  Keymap:  <leader>ss',
          '  Hint:    Space → s → s',
        },
        type = 'keymap', key = '<leader>ss',
        tip = '  <leader>ss shows all built-in pickers with descriptions.\n  Try it to discover pickers like spell_suggest or man_pages.',
        xp = 100, time_stars = { 5, 15, 45 },
      },
      {
        id = 'close_quiz', title = 'Escape Artist', mission = 'Close a picker without opening anything?',
        body = {
          'You\'re in insert mode inside a Telescope picker.',
          'How do you close it without opening any file?',
          '',
          '  [1]  :q<CR>',
          '  [2]  Ctrl+c  or  Esc',
          '  [3]  q',
          '  [4]  Ctrl+w',
        },
        type = 'quiz', answer = '2',
        explanation = '  <C-c> or <Esc>  close from insert mode\n  From normal mode (Esc first), q also works.\n  :q won\'t work — Telescope uses its own input loop.',
        xp = 75,
      },
      {
        id = 'quickfix_quiz', title = 'Quickfix Sender', mission = 'Multi-select and send to quickfix?',
        body = {
          'You want to mark multiple results in a picker',
          'and send them all to the quickfix list.',
          '',
          '  [1]  Ctrl+a to select all, then Enter',
          '  [2]  Tab to mark each, then Ctrl+q',
          '  [3]  Space to mark each, then Ctrl+q',
          '  [4]  Ctrl+m to enter multi-mode',
        },
        type = 'quiz', answer = '2',
        explanation = '  <Tab>  toggle selection on current result\n  <C-q>  send all selected to quickfix list\n  Then use :cn / :cp to navigate quickfix entries.',
        xp = 75,
      },
    },
  },
  {
    name = 'Power User',
    icon = '🏆',
    desc = 'Advanced pickers and search tricks',
    challenges = {
      {
        id = 'sdot', title = 'Recent Files', mission = 'Browse recently opened files',
        body = {
          'Jump back to files from this or past sessions.',
          'Works even after restarting Neovim.',
          '',
          '  Keymap:  <leader>s.',
          '  Hint:    Space → s → . (dot)',
        },
        type = 'keymap', key = '<leader>s.',
        tip = '  <leader>s. uses oldfiles, powered by Neovim\'s\n  shada file. Persists across restarts.',
        xp = 100, time_stars = { 5, 15, 45 },
      },
      {
        id = 'slash', title = 'Buffer Search', mission = 'Fuzzy-search inside the current buffer',
        body = {
          'Fuzzy search across the current buffer — faster',
          'than /search when you can\'t recall exact spelling.',
          '',
          '  Keymap:  <leader>/',
          '  Hint:    Space → / (forward-slash)',
        },
        type = 'keymap', key = '<leader>/',
        tip = '  <leader>/ uses a dropdown theme and no previewer.\n  Jump to any line by fuzzy-matching its content.',
        xp = 100, time_stars = { 5, 15, 45 },
      },
      {
        id = 'sk', title = 'Keymap Finder', mission = 'Search all active keymaps',
        body = {
          'Forgot what a key does? Fuzzy-search all keymaps',
          'including plugin mappings.',
          '',
          '  Keymap:  <leader>sk',
          '  Hint:    Space → s → k',
        },
        type = 'keymap', key = '<leader>sk',
        tip = '  <leader>sk shows mode, lhs, rhs, and description.\n  Filter by mode by typing e.g. "n " at the start.',
        xp = 100, time_stars = { 5, 15, 45 },
      },
      {
        id = 'word_quiz', title = 'Word Hunter', mission = 'Grep for the word under cursor?',
        body = {
          'Your cursor is on a function name. You want to',
          'grep for it across all project files — without',
          'typing it out. Which keymap?',
          '',
          '  [1]  <leader>sg  (then retype the word)',
          '  [2]  <leader>sw  (grep_string, uses cursor word)',
          '  [3]  <leader>sf  (find_files)',
          '  [4]  *  then  <leader>sg',
        },
        type = 'quiz', answer = '2',
        explanation = '  <leader>sw runs grep_string, which automatically\n  grabs the word under the cursor as the search term.\n  Also works in visual mode to search selected text.',
        xp = 75,
      },
      {
        id = 'sd', title = 'Diagnostics', mission = 'Browse all LSP diagnostics',
        body = {
          'Browse errors, warnings, and hints across your',
          'project using Telescope. Faster than jumping',
          'through them one by one.',
          '',
          '  Keymap:  <leader>sd',
          '  Hint:    Space → s → d',
        },
        type = 'keymap', key = '<leader>sd',
        tip = '  <leader>sd scopes to the current buffer by default.\n  Pass { bufnr = 0 } or leave empty for workspace-wide.',
        xp = 100, time_stars = { 5, 15, 45 },
      },
    },
  },
}
